package org.epl.parser;
import org.epl.core.Action;

/* Generated By:JJTree: Do not edit this line. ASTAction.java */

/**
 * Represents the Action production in the EPL grammar.
 * <pre>
 * Action ::= "action" &lt;ID&gt; "is" {@link ASTBlock Block}
 * </pre>  
 * 
 * @see ASTBlock
 */
public class ASTAction extends SimpleNode implements Action {
	String name;
	
  public ASTAction(int id) {
    super(id);
  }

  public ASTAction(EplParser p, int id) {
    super(p, id);
  }

	public void interpret() {
		super.interpret();
		bus.actions.put(name, this);
	}

	public void execute() {
		if (EplParser.debug) System.out.println("Action " + name + " invoked...");
		jjtGetChild(0).interpret();
	}

	
}
