package org.epl.parser;

/* Generated By:JJTree: Do not edit this line. ASTS.java */
/**
 * Represents the S production in the EPL grammar.  This is the start symbol for the language.
 * <pre>
 * S ::= ( {@link ASTStmt Stmt} ";" )+
 * </pre>
 * @see ASTStmt
 */

public class ASTS extends SimpleNode {
  public ASTS(int id) {
    super(id);
  }

  public ASTS(EplParser p, int id) {
    super(p, id);
  }

	
	public void interpret() {
		// Evaluate all of the statements in the program
	     int i, k = jjtGetNumChildren();

	     for (i = 0; i < k; i++)
	        jjtGetChild(i).interpret();
	     
	     bus.start();
	}

}
