package org.epl.parser;

/* Generated By:JJTree: Do not edit this line. ASTStmt.java */
/**
 * Represents the Stmt production in the EPL grammar.
 * <pre>
 * Stmt ::= {@link ASTPrint Print}
 *        | {@link ASTExecute Execute}
 *        | {@link ASTForeach Foreach}
 *        | {@link ASTIf If}
 *        | {@link ASTListener Listener}
 *        | {@link ASTBroker Broker}
 *        | {@link ASTCondition Condition}
 *        | {@link ASTAction Action}
 *        | {@link ASTSituation Situation}
 * </pre>
 * @see ASTPrint
 * @see ASTExecute
 * @see ASTForeach
 * @see ASTIf
 * @see ASTListener
 * @see ASTBroker
 * @see ASTCondition
 * @see ASTAction
 * @see ASTSituation
 */

public class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(EplParser p, int id) {
    super(p, id);
  }

  
	public void interpret() {
	  	if (EplParser.debug) System.out.println("In interpret() of " + this.getClass().getName());
		jjtGetChild(0).interpret();
	}
}
