/* Generated By:JJTree: Do not edit this line. org\epl\parser\EplParserTreeConstants.java */

package org.epl.parser;

public interface EplParserTreeConstants
{
  public int JJTS = 0;
  public int JJTSTMT = 1;
  public int JJTEXECUTE = 2;
  public int JJTPARAM = 3;
  public int JJTPARAMS = 4;
  public int JJTLISTENER = 5;
  public int JJTBROKER = 6;
  public int JJTPRINT = 7;
  public int JJTPRINTCATENATION = 8;
  public int JJTPRINTEXPR = 9;
  public int JJTEXPR = 10;
  public int JJTVAREXPR = 11;
  public int JJTCONDITION = 12;
  public int JJTCONDITIONAL = 13;
  public int JJTNOTCONDITIONAL = 14;
  public int JJTORCONDITIONAL = 15;
  public int JJTANDCONDITIONAL = 16;
  public int JJTBLOCK = 17;
  public int JJTACTION = 18;
  public int JJTLIST = 19;
  public int JJTSITUATION = 20;
  public int JJTFOREACH = 21;
  public int JJTIF = 22;


  public String[] jjtNodeName = {
    "S",
    "Stmt",
    "Execute",
    "Param",
    "Params",
    "Listener",
    "Broker",
    "Print",
    "PrintCatenation",
    "PrintExpr",
    "Expr",
    "VarExpr",
    "Condition",
    "Conditional",
    "NotConditional",
    "OrConditional",
    "AndConditional",
    "Block",
    "Action",
    "List",
    "Situation",
    "Foreach",
    "If",
  };
}
