/* Generated By:JJTree&JavaCC: Do not edit this line. EplParserConstants.java */
package org.epl.parser;

public interface EplParserConstants {

  int EOF = 0;
  int EXECUTE = 5;
  int LISTENER = 6;
  int CONDITION = 7;
  int ACTION = 8;
  int FOREACH = 9;
  int BLOCK = 10;
  int BROKER = 11;
  int PRINT = 12;
  int FOR = 13;
  int IN = 14;
  int IS = 15;
  int WHEN = 16;
  int DO = 17;
  int IF = 18;
  int WITHIN = 19;
  int OR = 20;
  int AND = 21;
  int NOT = 22;
  int AS = 23;
  int ID = 24;
  int STRING = 25;
  int DIGITS = 26;
  int LINE_COMMENT = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"execute\"",
    "\"listener\"",
    "\"condition\"",
    "\"action\"",
    "\"foreach\"",
    "\"block\"",
    "\"broker\"",
    "\"print\"",
    "\"for\"",
    "\"in\"",
    "\"is\"",
    "\"when\"",
    "\"do\"",
    "\"if\"",
    "\"within\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"as\"",
    "<ID>",
    "<STRING>",
    "<DIGITS>",
    "<LINE_COMMENT>",
    "\";\"",
    "\"+\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
